# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/C++.gitlab-ci.yml

# use the official gcc image, based on debian
# can use versions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/

image: cxx_boilerplate_image

variables:
  GIT_DEPTH: 7
  GIT_SUBMODULE_DEPTH: 3
  GIT_SUBMODULE_STRATEGY: recursive
  CI_DEBUG_SERVICES: "true"
  FF_NETWORK_PER_BUILD: "true"
stages:
  - build_base_image
  - lint
  - build
  - profile
  - sanitize
  - test
  - deploy
  - manual


clang_format:
  stage: lint
  needs: []
  script:
    - find . -not \( -path ./external -prune \) -not \( -path ./libraries/appbase -prune \) -name "*.cpp" -o -name "*.cc" -o -name "*.h" -o -name "*.hpp"
    - find . -not \( -path ./external -prune \) -not \( -path ./libraries/appbase -prune \) -name "*.cpp" -o -name "*.cc" -o -name "*.h" -o -name "*.hpp" |
      xargs -n 1 clang-format -style=llvm --dry-run -Werror


cmakelint:
  stage: lint
  needs: []
  script:
    - pip install --upgrade pip
    - pip install cmakelint
    - find . -not \( -path ./external -prune \) -not \( -path ./libraries/appbase -prune \) -name "CMakeLists.txt" | xargs -I {} cmakelint {}


build_gcc:
  stage:
    build
  variables:
    CC: "/usr/bin/gcc"
    CXX: "/usr/bin/g++"
  script:
    - rm build -rf
    - cmake -B build -D CMAKE_BUILD_TYPE=Debug
    - cmake --build build
  artifacts:
      name: "$CI_JOB_NAME"
      paths:
        - build


build_clang:
  stage:
    build
  variables:
    CC: "/usr/bin/clang"
    CXX: "/usr/bin/clang++"
  script:
    - rm build -rf
    - cmake -B build -D CMAKE_BUILD_TYPE=Debug
    - cmake --build build
  artifacts:
      name: "$CI_JOB_NAME"
      paths:
        - build


bind_build_cxx_boilerplate_base_image_automatic:
  stage: build_base_image
  image: docker:24.0.1-cli
  script:
    - apk add bash git
    - docker version
    - docker context ls
    - >
      if docker images | grep cxx_boilerplate_image ; then
        echo "cxx_boilerplate_image already exists"
      else
        $CI_PROJECT_DIR/scripts/build_ci_base_image.sh $CI_COMMIT_SHA 
      fi
    - $CI_PROJECT_DIR/scripts/export-binaries.sh cxx_boilerplate_image $CI_PROJECT_DIR/build
    - docker builder prune --force
  artifacts:
      name: "$CI_JOB_NAME"
      paths:
        - build


google_benchmark:
  stage:
    test
  script:
    - time build/tests/example_test --gtest_shuffle --gtest_repeat=10
    - time build/tests/example2_test
    - time external/gtest-parallel/gtest-parallel build/tests/example2_test --workers=$(nproc)
  dependencies: [build_gcc]


cachegrind_valgrind:
  stage:
    profile
  script:
    - time build/tests/example_test --gtest_shuffle --gtest_repeat=10
    - time build/tests/example2_test
    - time external/gtest-parallel/gtest-parallel build/tests/example2_test --workers=$(nproc)
  dependencies: [build_gcc]


callgrind_valgrind:
  stage:
    profile
  script:
    - time build/tests/example_test --gtest_shuffle --gtest_repeat=10
    - time build/tests/example2_test
    - time external/gtest-parallel/gtest-parallel build/tests/example2_test --workers=$(nproc)
  dependencies: [build_gcc]


perf:
  stage:
    profile
  script:
    - time build/tests/example_test --gtest_shuffle --gtest_repeat=10
    - time build/tests/example2_test
    - time external/gtest-parallel/gtest-parallel build/tests/example2_test --workers=$(nproc)


address_gcc:
  stage:
    sanitize
  variables:
    CC: "/usr/bin/gcc"
    CXX: "/usr/bin/g++"
  script:
    - rm build -rff
    - cmake -B build -D CMAKE_BUILD_TYPE=Debug -D SANITIZE_ADDRESS=ON
    - cmake --build build --target address_invalid_test
    - build/tests/address_invalid_test || true
    - bash -c 'build/tests/address_invalid_test 2>&1 | grep stack-buffer-overflow'
  artifacts:
      name: "$CI_JOB_NAME"
      paths:
        - build


memcheck_valgrind:
  stage:
    sanitize
  variables:
    CC: "/usr/bin/gcc"
    CXX: "/usr/bin/g++"
  script:
    - rm build -rff
    - cmake -B build -D CMAKE_BUILD_TYPE=Debug -D SANITIZE_ADDRESS=OFF
    - cmake --build build --target address_invalid_test
    - valgrind --leak-check=full --show-error-list=yes --show-leak-kinds=all --track-origins=yes --error-exitcode=87 build/tests/address_invalid_test || true
    - bash -c 'valgrind --leak-check=full --show-error-list=yes --show-leak-kinds=all --track-origins=yes build/tests/address_invalid_test 2>&1 | grep "7 errors"'
  artifacts:
      name: "$CI_JOB_NAME"
      paths:
        - build


hellgrind_valgrind:
  stage:
    sanitize
  script:
    - time build/tests/example_test --gtest_shuffle --gtest_repeat=10
    - time build/tests/example2_test
    - time external/gtest-parallel/gtest-parallel build/tests/example2_test --workers=$(nproc)
  dependencies: [build_gcc]


gcov:
  stage:
    sanitize
  script:
    - time build/tests/example_test --gtest_shuffle --gtest_repeat=10
    - time build/tests/example2_test
    - time external/gtest-parallel/gtest-parallel build/tests/example2_test --workers=$(nproc)
  dependencies: [build_gcc]


lcov:
  stage:
    sanitize
  script:
    - time build/tests/example_test --gtest_shuffle --gtest_repeat=10
    - time build/tests/example2_test
    - time external/gtest-parallel/gtest-parallel build/tests/example2_test --workers=$(nproc)
  dependencies: [build_gcc]


example_test:
  stage:
    test
  script:
    - time build/tests/example_test --gtest_shuffle --gtest_repeat=10
    - time build/tests/example2_test
    - time external/gtest-parallel/gtest-parallel build/tests/example2_test --workers=$(nproc)
  dependencies: [build_gcc]


example_service:
  stage:
    test
  needs: []
  services:
    - name: postgres
      alias: db
  variables:
    POSTGRES_DB: custom_db
    POSTGRES_USER: custom_user
    POSTGRES_PASSWORD: custom_pass
  script:
    - pip install --upgrade pip
    - pip install "psycopg[binary,pool]"
    - pip install pgcli
    - echo "SELECT VERSION();" | pgcli "postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB"


show_version:
  stage:
    test
  script:
    - build/programs/tools/show_version
  dependencies: [build_gcc]


bind_build_cxx_boilerplate_base_image_manual:
  stage: manual
  needs: []
  image: docker:24.0.1-cli
  rules:
    - when: manual
  script:
    - apk add bash git
    - docker version
    - docker context ls
    - $CI_PROJECT_DIR/scripts/build_ci_base_image.sh $CI_COMMIT_SHA 
    - $CI_PROJECT_DIR/scripts/export-binaries.sh cxx_boilerplate_image:$CI_COMMIT_SHA $CI_PROJECT_DIR/build
    - docker builder prune --force
  artifacts:
      name: "$CI_JOB_NAME"
      paths:
        - build
