# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/C++.gitlab-ci.yml

# use the official gcc image, based on debian
# can use versions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/

image: ubuntu

variables:
  GIT_DEPTH: 7
  GIT_SUBMODULE_DEPTH: 3
  GIT_SUBMODULE_STRATEGY: "recursive"
  CI_DEBUG_SERVICES: "true"
  FF_NETWORK_PER_BUILD: "true"
stages:
  - build
  - test
  - deploy


example_build:
  stage:
    build
  script:
    - apt update && apt install -y git build-essential cmake
    - cmake -B build -D CMAKE_BUILD_TYPE=Debug
    - cmake --build build
    - build/tests/example_test --gtest_shuffle --gtest_repeat=10
    - sleep 10
  artifacts:
      name: "$CI_JOB_NAME"
      paths:
        - build/tests/example_test
        - build/tests/second_example_test


example_test:
  stage:
    test
  script:
    - apt update && apt install python3 python-is-python3 pip -y
    - time build/tests/second_example_test
    - time external/gtest-parallel/gtest-parallel build/tests/second_example_test --workers=$(nproc)
  dependencies: [example_build]


example_service:
  stage:
    test
  services:
    - name: postgres
      alias: db
  variables:
    POSTGRES_DB: custom_db
    POSTGRES_USER: custom_user
    POSTGRES_PASSWORD: custom_pass
  script:
    - apt update && apt install python3 python-is-python3 pip -y
    - pip install --upgrade pip
    - pip install "psycopg[binary,pool]"
    - pip install pgcli
    - echo "SELECT VERSION();" | pgcli "postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@db:5432/$POSTGRES_DB"


clang_format:
  stage: test
  needs: []
  script:
    - apt update && apt install -y git build-essential cmake clang-format clang-tidy
    - find . -not \( -path ./external -prune \) -name "*.cpp" -o -name "*.cc" -o -name "*.h" -o -name "*.hpp"
    - find . -not \( -path ./external -prune \) -name "*.cpp" -o -name "*.cc" -o -name "*.h" -o -name "*.hpp" |
      xargs -n 1 clang-format -style=llvm --dry-run -Werror


cmakelint:
  stage: test
  needs: []
  script:
    - apt update && apt install python3 python-is-python3 pip -y
    - pip install --upgrade pip
    - pip install cmakelint
    - find . -not \( -path ./external -prune \) -name "CMakeLists.txt" | xargs -I {} cmakelint {}


bind_build_forgottensorcery_base_image:
  stage: build
  image: docker:23.0.6
  rules:
    - when: manual
  script:
    - apk add bash git
    - git config --global --add safe.directory '*'
    - "$CI_PROJECT_DIR/scripts/build_ci_base_image.sh"
    - docker builder prune --force    
